name: mlhivemind
favicon: null
layout_spectrum: 0.8197101440746337
typography_spectrum: 0.6802982180379331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3111906801350415
  lightness: 0.5233359062112868
  saturation: 0.9084417454432696
  rhythmicContrast: 0.9239791026338935
purpose: []
